### ISSUE TITLE
Convert pointclouds' txt files to npy format

### ISSUE THREAD

**Issue by YznMur** [Artisense-ai/libartipy#1]
Hi
Thanks for your open source code, however I have a small question
How can I convert pointclouds' txt files of dataset 4Seasons to .npy format?

**Comment by pmwenzel** [comment]
Hi @YznMur, currently we only support the conversion of point clouds into the following formats (LAS, PLY, H5, PCD, CSV). See https://github.com/Artisense-ai/libartipy/blob/main/libartipy/pointcloud/pointcloud3D.py.
However, please feel free to adjust the script and export the point clouds to `.npy` format.
